#!/usr/bin/env ruby

SINATRA_ROOT = File.expand_path('..', File.dirname(__FILE__))

irb = (RUBY_PLATFORM =~ /(:?mswin|mingw)/) ? 'irb.bat' : 'irb'

exec("#{irb} --readline -I #{SINATRA_ROOT}/lib -r irb/completion --prompt-mode simple -r rubygems -r runit-man/app")
